server:
  port: 8080

logging:
  level:
    org.springframework: INFO
    org.hibernate: INFO

spring:
  application:
    name: recipes-app
    main:
      banner-mode: off
    web:
      resources:
        add-mappings: false

  datasource:
     url: jdbc:postgresql://localhost:5432/postgres
     username: postgres
     password: ale1oana0
  sql:
    init:
      mode: never

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  jpa:
    hibernate:
      ddl-auto: none
      jdbc:
        time_zone: Europe/Bucharest

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 86400000

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /management
      exposure:
        include: "*"